version: '3.2'
services:
  # Set up Microsoft SQL Server (Express)
  #
  # On mac OS, make sure your docker engine has enough memory,
  # MS SQL will require at least 2GB of memory for itself and
  # the other containers need some space too. Tested with 8GB
  # and that seemed to be enough. (Docker engine > Preferences
  # > Advanced tab)
  #
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-CU12-ubuntu"
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=VeryVeryS3cret"
      - "MSSQL_PID=Express"
    volumes:
      - type: volume
        source: mssql_data
        target: /var/opt/mssql

  # Set up Elasticsearch
  #
  # Default JVM memory is 1GB, runs better with 2GB when any
  # realistic indexes are in use.
  #
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.4"
    container_name: elasticsearch
    environment:
      - cluster.name=elastic.dev
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch

  # Set up ElasticHQ for easy management and monitoring
  # See https://github.com/ElasticHQ/elasticsearch-HQ
  #
  # Browse to http://localhost:5000 and select the
  # default cluster (from address http://elasticsearch:9200)
  #
  elastichq:
    image: "elastichq/elasticsearch-hq"
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
    ports:
      - "5000:5000"

# Volume specifications for container data
volumes:
  mssql_data:
  elasticsearch_data:
